# These are supported funding model platforms
github: # Replace with github username
patreon: # Replace with patreon username
open_collective: # Replace with open collective username
custom: # Replace with custom url\n