#!/bin/bash

echo "🚀 Setting up GitHub Repository Metadata..."
echo "Note: Make sure you have pushed an initial commit to GitHub before running this script."
echo "Press Ctrl+C to cancel if you haven't pushed yet, or press Enter to continue."
read

# 1. Create Labels
echo "Creating Labels..."
gh label create "good first issue" --color "7057ff" --description "Good for newcomers" --force || true
gh label create "help wanted" --color "008672" --description "Extra attention is needed" --force || true
gh label create "bug" --color "d73a4a" --description "Something isn't working" --force || true
gh label create "enhancement" --color "a2eeef" --description "New feature or request" --force || true
gh label create "documentation" --color "0075ca" --description "Improvements or additions to documentation" --force || true
gh label create "research" --color "c2e0c6" --description "Requires domain research" --force || true
gh label create "design" --color "bfd4f2" --description "UI/UX and visual design" --force || true
gh label create "architecture" --color "d4c5f9" --description "System design and architecture" --force || true
gh label create "discussion" --color "d876e3" --description "Open for discussion" --force || true
gh label create "frontend" --color "fbca04" --description "Frontend/Client side" --force || true
gh label create "backend" --color "f9d0c4" --description "Backend/Server side" --force || true
gh label create "mobile" --color "ffc58f" --description "Mobile app related" --force || true
gh label create "testing" --color "bfd4f2" --description "Unit, integration, and e2e testing" --force || true
gh label create "high priority" --color "b60205" --description "Needs to be addressed immediately" --force || true
gh label create "low priority" --color "ffffff" --description "Can be addressed later" --force || true

# 2. Create Milestones
echo "Creating Milestones..."
gh api repos/:owner/:repo/milestones -f title="Foundation" -f state="open" -f description="Core repo setup and research" || true
gh api repos/:owner/:repo/milestones -f title="Research" -f state="open" -f description="Financial modeling and logic definitions" || true
gh api repos/:owner/:repo/milestones -f title="Architecture" -f state="open" -f description="System design and engine planning" || true
gh api repos/:owner/:repo/milestones -f title="MVP" -f state="open" -f description="Minimum Viable Product" || true
gh api repos/:owner/:repo/milestones -f title="Alpha" -f state="open" -f description="Internal testing release" || true
gh api repos/:owner/:repo/milestones -f title="Beta" -f state="open" -f description="Public beta release" || true
gh api repos/:owner/:repo/milestones -f title="Version 1.0" -f state="open" -f description="First stable release" || true

# 3. Create Research Issues
echo "Creating Research Issues..."
gh issue create --title "[RESEARCH] How should salary progression work across different career paths?" --body "This is a placeholder issue for researching: How should salary progression work across different career paths?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should inflation affect users' purchasing power?" --body "This is a placeholder issue for researching: How should inflation affect users' purchasing power?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should investments use historical market data or simulated random walks?" --body "This is a placeholder issue for researching: Should investments use historical market data or simulated random walks?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should health insurance work?" --body "This is a placeholder issue for researching: How should health insurance work?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should income taxes differ across countries/regions?" --body "This is a placeholder issue for researching: How should income taxes differ across countries/regions?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should random life events (e.g., medical emergencies, car accidents) be modeled?" --body "This is a placeholder issue for researching: How should random life events (e.g., medical emergencies, car accidents) be modeled?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How does education level correlate with income potential in the simulation?" --body "This is a placeholder issue for researching: How does education level correlate with income potential in the simulation?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What is the impact of student loans on early career finances?" --body "This is a placeholder issue for researching: What is the impact of student loans on early career finances?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should property value appreciation be calculated?" --body "This is a placeholder issue for researching: How should property value appreciation be calculated?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should the cost of raising children be modeled over time?" --body "This is a placeholder issue for researching: How should the cost of raising children be modeled over time?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should we model different types of debt (credit cards, personal loans, mortgages)?" --body "This is a placeholder issue for researching: Should we model different types of debt (credit cards, personal loans, mortgages)?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do macroeconomic cycles (recessions, booms) affect the user?" --body "This is a placeholder issue for researching: How do macroeconomic cycles (recessions, booms) affect the user?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should retirement accounts (401k, IRA, pension) be differentiated?" --body "This is a placeholder issue for researching: How should retirement accounts (401k, IRA, pension) be differentiated?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What happens when a user goes bankrupt in the simulation?" --body "This is a placeholder issue for researching: What happens when a user goes bankrupt in the simulation?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should cost of living vary by simulated geographic location?" --body "This is a placeholder issue for researching: How should cost of living vary by simulated geographic location?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should we include behavioral finance factors (e.g., impulse buying)?" --body "This is a placeholder issue for researching: Should we include behavioral finance factors (e.g., impulse buying)?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How is credit score calculated and what does it impact?" --body "This is a placeholder issue for researching: How is credit score calculated and what does it impact?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should capital gains taxes be implemented?" --body "This is a placeholder issue for researching: How should capital gains taxes be implemented?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we model the gig economy and freelance income?" --body "This is a placeholder issue for researching: How do we model the gig economy and freelance income?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should cryptocurrency and high-risk investments be included?" --body "This is a placeholder issue for researching: Should cryptocurrency and high-risk investments be included?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What are the financial impacts of marriage and divorce?" --body "This is a placeholder issue for researching: What are the financial impacts of marriage and divorce?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should unemployment periods and severance packages work?" --body "This is a placeholder issue for researching: How should unemployment periods and severance packages work?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we model natural disasters and home insurance?" --body "This is a placeholder issue for researching: How do we model natural disasters and home insurance?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should we simulate the effects of inflation on different asset classes separately?" --body "This is a placeholder issue for researching: Should we simulate the effects of inflation on different asset classes separately?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we account for systemic biases or socioeconomic starting conditions?" --body "This is a placeholder issue for researching: How do we account for systemic biases or socioeconomic starting conditions?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should inheritance and generational wealth be handled?" --body "This is a placeholder issue for researching: How should inheritance and generational wealth be handled?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What are the rules for early withdrawal penalties on retirement accounts?" --body "This is a placeholder issue for researching: What are the rules for early withdrawal penalties on retirement accounts?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should variable vs. fixed-rate mortgages behave?" --body "This is a placeholder issue for researching: How should variable vs. fixed-rate mortgages behave?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should we model the cost of eldercare or supporting parents?" --body "This is a placeholder issue for researching: Should we model the cost of eldercare or supporting parents?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do government welfare programs factor into the simulation?" --body "This is a placeholder issue for researching: How do government welfare programs factor into the simulation?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What is the economic impact of renting vs. buying a home over 30 years?" --body "This is a placeholder issue for researching: What is the economic impact of renting vs. buying a home over 30 years?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we model depreciation of assets like cars?" --body "This is a placeholder issue for researching: How do we model depreciation of assets like cars?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should disability insurance and long-term care be handled?" --body "This is a placeholder issue for researching: How should disability insurance and long-term care be handled?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should we simulate entrepreneurship and business failure rates?" --body "This is a placeholder issue for researching: Should we simulate entrepreneurship and business failure rates?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How does currency exchange affect international users or scenarios?" --body "This is a placeholder issue for researching: How does currency exchange affect international users or scenarios?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What is the formula for calculating property taxes based on location?" --body "This is a placeholder issue for researching: What is the formula for calculating property taxes based on location?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should utility costs and maintenance scale with home ownership?" --body "This is a placeholder issue for researching: How should utility costs and maintenance scale with home ownership?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we model the psychological toll of high debt (if at all)?" --body "This is a placeholder issue for researching: How do we model the psychological toll of high debt (if at all)?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should we simulate the impact of automation/AI on job security?" --body "This is a placeholder issue for researching: Should we simulate the impact of automation/AI on job security?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do different savings accounts (high-yield vs. standard) operate?" --body "This is a placeholder issue for researching: How do different savings accounts (high-yield vs. standard) operate?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What are the financial costs of continuing education or career switching?" --body "This is a placeholder issue for researching: What are the financial costs of continuing education or career switching?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should stock dividends and reinvestment be modeled?" --body "This is a placeholder issue for researching: How should stock dividends and reinvestment be modeled?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we handle peer pressure or lifestyle creep in the simulation?" --body "This is a placeholder issue for researching: How do we handle peer pressure or lifestyle creep in the simulation?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should there be varying levels of financial literacy for the character vs. the player?" --body "This is a placeholder issue for researching: Should there be varying levels of financial literacy for the character vs. the player?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we accurately reflect the cost of public vs. private education?" --body "This is a placeholder issue for researching: How do we accurately reflect the cost of public vs. private education?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How should state vs. federal taxes be decoupled?" --body "This is a placeholder issue for researching: How should state vs. federal taxes be decoupled?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] What is the financial impact of having a criminal record in the simulation?" --body "This is a placeholder issue for researching: What is the financial impact of having a criminal record in the simulation?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we model inflation's impact on fixed-income retirees?" --body "This is a placeholder issue for researching: How do we model inflation's impact on fixed-income retirees?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] Should we include the economics of starting a family later vs. earlier?" --body "This is a placeholder issue for researching: Should we include the economics of starting a family later vs. earlier?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true
gh issue create --title "[RESEARCH] How do we validate our financial models against real-world data?" --body "This is a placeholder issue for researching: How do we validate our financial models against real-world data?. Please add data, links, and formulas here." --label "research" --label "help wanted" || true

# 4. Create Design Issues
echo "Creating Design Issues..."
gh issue create --title "[DESIGN] Dashboard UX layout for the main simulation screen" --body "This is a placeholder issue for designing: Dashboard UX layout for the main simulation screen. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Timeline visualization for 50+ years of simulated life" --body "This is a placeholder issue for designing: Timeline visualization for 50+ years of simulated life. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Monthly/Yearly financial report summary design" --body "This is a placeholder issue for designing: Monthly/Yearly financial report summary design. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Financial graphs for net worth progression over time" --body "This is a placeholder issue for designing: Financial graphs for net worth progression over time. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Achievement system badges and unlock UX" --body "This is a placeholder issue for designing: Achievement system badges and unlock UX. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Notification system for random life events" --body "This is a placeholder issue for designing: Notification system for random life events. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] User Profile and character stats screen" --body "This is a placeholder issue for designing: User Profile and character stats screen. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Settings page for simulation parameters" --body "This is a placeholder issue for designing: Settings page for simulation parameters. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Onboarding flow for new players" --body "This is a placeholder issue for designing: Onboarding flow for new players. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Scenario selection menu" --body "This is a placeholder issue for designing: Scenario selection menu. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Investment portfolio breakdown chart" --body "This is a placeholder issue for designing: Investment portfolio breakdown chart. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Budget allocation sliders for monthly expenses" --body "This is a placeholder issue for designing: Budget allocation sliders for monthly expenses. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Mortgage and loan calculator pop-up interface" --body "This is a placeholder issue for designing: Mortgage and loan calculator pop-up interface. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Job market and career selection screen" --body "This is a placeholder issue for designing: Job market and career selection screen. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Real estate purchasing interface" --body "This is a placeholder issue for designing: Real estate purchasing interface. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] End of Life summary and score screen" --body "This is a placeholder issue for designing: End of Life summary and score screen. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Dark mode vs. light mode color palettes" --body "This is a placeholder issue for designing: Dark mode vs. light mode color palettes. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Mobile responsive layout for the main dashboard" --body "This is a placeholder issue for designing: Mobile responsive layout for the main dashboard. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Typography selection for readability of complex financial data" --body "This is a placeholder issue for designing: Typography selection for readability of complex financial data. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Iconography for different expense categories" --body "This is a placeholder issue for designing: Iconography for different expense categories. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Tooltip system for explaining complex financial terms" --body "This is a placeholder issue for designing: Tooltip system for explaining complex financial terms. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Taxation breakdown infographic UI" --body "This is a placeholder issue for designing: Taxation breakdown infographic UI. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Education and skill-tree UI" --body "This is a placeholder issue for designing: Education and skill-tree UI. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] News ticker for macroeconomic events" --body "This is a placeholder issue for designing: News ticker for macroeconomic events. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Shopping and major purchase catalog interface" --body "This is a placeholder issue for designing: Shopping and major purchase catalog interface. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Bank statement and transaction history log" --body "This is a placeholder issue for designing: Bank statement and transaction history log. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Credit score speedometer/gauge design" --body "This is a placeholder issue for designing: Credit score speedometer/gauge design. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Avatar customization for the simulated character" --body "This is a placeholder issue for designing: Avatar customization for the simulated character. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Loading screens with financial literacy tips" --body "This is a placeholder issue for designing: Loading screens with financial literacy tips. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true
gh issue create --title "[DESIGN] Accessibility (a11y) design for colorblindness and screen readers" --body "This is a placeholder issue for designing: Accessibility (a11y) design for colorblindness and screen readers. Please attach wireframes, mockups, or Figma links." --label "design" --label "help wanted" || true

echo "✅ GitHub Setup Complete!"
